#!/bin/sh

# Help for duneproc users.

OPT=$1

if [ -z "$OPT" ]; then
  echo $0 OPT
  echo "  OPT = general for general commands"
  echo "  OPT = pdsp for protoDUNE commands"
  echo "  OPT = ib for Iceberg commands"
  echo "  OPT = ibex fpr Iceberg examples"
  echo "  OPT = ibex fpr Iceberg examples"
  if [ -r README.txt ]; then
    echo "  OPT = local for local help (README.txt)"
  fi
  exit 0
fi

echo
if [ $OPT = local -a -r README.txt ]; then
  cat README.txt
elif [ $OPT = general ]; then
  echo "getGridProxy - Fetches a kerberos-based grid certificate.
elif [ $OPT = pdsp ]; then
  echo "pdspRunFileCount - Returns the # raw data files for PDSP run."
  echo "pdspRunLfn - Returns one raw data LFN for a PDSP run."
  echo "pdspShowMetadata - Show the SAM metadata for a PDSP file or run."
  echo "pdspStartTime - Returns the WIB count for a PDSP file."
  echo "pdspDataStream - Returns the data stream name for a PDSP file."
  echo "pdspWibCount - Returns the WIB count for a PDSP run."
elif [ $OPT = ib ]; then
  echo "showMetadata - Displays metatdata for a file or an Iceberg run"
  echo "ibDaqConfig - Display DAQ config string for Iceberg runs"
  echo
  echo "ibFindFiles - Build a dataset (file list) for run."
  echo "ibGroupRuns - Build a dataset for a series of runs"
  echo "ibStageFiles - Stage files for a series of runs"
  echo
  echo "ibRunPeriod - Display the run period for a run."
  echo "ibRunPeriodRuns - Display the runs for a run period."
  echo
  echo "savedqmi - Copy iceberg DQM results"
  echo "ibSaveWfRaw - Copy iceberg waveforms to web area"
elif [ $OPT = ibex ]; then
  echo "Example Iceberg processing commands:"
  echo
  echo Run dataprep with no tools and display trigger flags and channel counts:
  echo "  duneproc run_dataprep_iceberg/setIceberg5a iceberg008378"
  echo "  grep "Trigger flag:" run_dataprep_iceberg/setIceberg5a/iceberg008378/event000001/run.log"
  echo "  grep "All digit count" run_dataprep_iceberg/setIceberg5a/iceberg008378/run.log"
  echo
  echo Run DQM and post results
  echo "  duneproc run_iceberg5a_dqm1 iceberg008378/event000001"
  echo "  savedqmi 8378 1"
  echo
  echo Post waveforms:
  echo "  duneproc ibWfRaw/setIceberg5a iceberg008378/event000001"
  echo "  ibSaveWfRaw 8378 1"
  echo
  echo Generate and post pedestal distributions:
  echo "  duneproc run_iceberg5a_dqm1/showPeds iceberg008378/event000001"
  echo "  ibSavePeds 8378 1"
  echo
  echo Create ROI tree for calibrated data.
  echo "  duneproc run_dataprep_iceberg/setIceberg5a/dptools_calib/addRoiTree iceberg008372"
  echo "  root.exe run_dataprep_iceberg/setIceberg5a/dptools_calib/addRoiTree/iceberg008372/adcrois.root"
  echo "  root> drawRois(adcrois, \"status==0&&(hmax>0.9)\", \"x\")"
  echo "  root> drawRois(adcrois, \"status==0&&(hmin<-1.5||hmax>1.5)\", "uv")"
  echo "  root> drawSigstren(adcrois, \"channel>=800&&status==0&&hmax>1.3\")"
else
  echo Invalid option: $OPT
fi
echo
