#!/bin/sh

# findFilePnfs
#
# David Adams
# April 2020
#
# Return the pnfs location for a logical file name.

UPRE=^gsiftp://fndca1.fnal.gov:2811

INPATH=$1

# If name starts with /pnfs, assume it is valid.
if [[ $INPATH =~ "/pnfs/" ]]; then echo $INPATH; exit; fi

INFILE=$(basename $INPATH)
UFILES=$(samweb get-file-access-url $INFILE)
if [ -n "$UFILES" ]; then
  for UFILE in $UFILES; do
    if [[ $UFILE =~ ^$UPRE ]]; then
      PFILE=$(echo $UFILE | sed "s#$UPRE##g" | sed "s#/fnal.gov/usr/#/#g")
      echo $PFILE
    fi
  done
fi
