#!/bin/sh

# findFileXroot

INPATH=$1

# If name starts with xroot, assume it is valid.
if [[ $INPATH =~ "xroot:" ]]; then echo $INPATH; exit; fi

PFILE=$(findFilePnfs $INPATH)
XFILE=$(echo $PFILE | sed 's#/pnfs/#xroot://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/#g')
echo $XFILE
