#! /bin/sh

# ibDaqConfig
#
# David Adams
# March 2021
#
# Display the DAQ config strings for a series of Iceberg runs.

RUN1=$1
RUN2=$2
PAT1="$3"

if [ -z "$RUN1" ]; then
  echo Usage: $0 RUN1 [RUN2]
  exit 0
fi

if [ -z "$RUN2" ]; then
  RUN2=$RUN1
fi

RUN=$RUN1
RUC=0
EVC=0
START=
STOP=
while [ $RUN -le $RUN2 ]; do
  MDFILE=./md$RUN.tmp
  if showMetadata $RUN >$MDFILE; then
    if [ -z "$START" ]; then
      START="$(grep "Start Time" $MDFILE | sed 's/.*Start Time: //g')"
    fi
    STOP="$(grep "End Time" $MDFILE | sed 's/.*End Time: //g')"
    CNAM=$(grep DAQConfigName $MDFILE | sed 's/.*DAQConfigName: //g')
    NEVT=$(grep "Event Count" $MDFILE | sed 's/.*Event Count: //g')
    EVC=$(($EVC+$NEVT))
    RUC=$(($RUC+1))
    echo $RUN $CNAM $NEVT
  else
    echo "$RUN: ***** Metadata not found *****"
  fi
  rm $MDFILE
  RUN=$((RUN+1))
done
echo Runs $RUN1-$RUN2
echo "   Run count: $RUC"
echo " Event count: $EVC"
echo "       Start: $START"
echo "        Stop: $STOP"
