#!/bin/sh
#
# David Adams
# April 2020
#
# Find the list of raw data files for an Iceberg run.

RUN=$1
OUTDIR=$2

DEFDIR=$HOME/data/dune/datasets/iceberg
if [ -z "$RUN" ]; then
  echo Usage: $0 RUN DIR
  echo "  RUN is run number."
  echo "  DIR is the directory to write the file list."
  echo "  If DIR=\"-\", $DEFDIR is used."
  exit 0
fi

OUTFILE=
if [ -n "$OUTDIR" ]; then
  if [ $OUTDIR = "-" ]; then
    OUTDIR=$DEFDIR
  fi
  if [ -d $OUTDIR ]; then
    SRUN=$RUN
    while [ ${#SRUN} -lt 6 ]; do SRUN=0$SRUN; done
    OUTFILE=$OUTDIR/iceberg$SRUN.txt
    if [ -r $OUTFILE ]; then
      echo Output file already exists: $OUTFILE
      exit 2
    fi
  else
    echo Output directory not found: $OUTDIR
    exit 3
  fi
fi

RAWFILES=$(samweb list-files "run_type=iceberg and run_number=$RUN" | sort)
if [ -z "$RAWFILES" ]; then
  echo No files found for run $RUN.
  exit 1
fi
for RAWFILE in $RAWFILES; do
  echo $RAWFILE
  if [ -n "$OUTFILE" ]; then
    echo $RAWFILE >> $OUTFILE
  fi
done
if [ -n "$OUTFILE" ]; then
  echo Dataset written to $OUTFILE
fi
