#!/bin/sh

# ibRunPeriod
#
# David Adams
# August 2020
#
# Return the run period for and Iceberg run numnber.

RUN=$1
SHORT=$2

if [ -z "$1" ]; then
  echo Usage: $0 RUN >&2
  echo "       $0 RUN short" >&2
  echo "Latter returns dhortened period, e.g. 4 for 4b" >&2
  exit 1
fi

if [ $RUN -lt 5360 ]; then
  echo 3
else
  if [ "$2" = short ]; then
    SPER=$($0 $RUN)
    echo ${SPER:0:1}
  elif [ $RUN -lt 6100 ]; then
    echo 4a
  elif [ $RUN -lt 6100 ]; then
    echo 4b
  elif [ $RUN -lt 8249 ]; then
    echo test
  elif [ $RUN -lt 8409 ]; then
    echo 5a
  elif [ $RUN -lt 8416 ]; then
    echo test
  elif [ $RUN -lt 8432 ]; then
    echo 5b
  elif [ $RUN -lt 8453 ]; then
    echo 5c
  elif [ $RUN -lt 8474 ]; then
    echo 5d
  elif [ $RUN -lt 8620 ]; then
    echo 5c
  elif [ $RUN -lt 8630 ]; then
    echo 5d
  elif [ $RUN -lt 8635 ]; then
    echo 5c
  elif [ $RUN -lt 8639 ]; then
    echo 5e
  elif [ $RUN -lt 8640 ]; then
    echo 5c
  elif [ $RUN -lt 8645 ]; then
    echo 5e
  elif [ $RUN -lt 8646 ]; then
    echo 5c
  elif [ $RUN -lt 8646 ]; then
    echo 5c
  elif [ $RUN -lt 8651 ]; then
    echo 5e
  elif [ $RUN -lt 8652 ]; then
    echo 5c
  elif [ $RUN -lt 8655 ]; then
    echo 5d
  elif [ $RUN -lt 8657 ]; then
    echo 5e
  elif [ $RUN -lt 8658 ]; then
    echo 5c
  elif [ $RUN -lt 8662 ]; then
    echo 5e
  elif [ $RUN -lt 8663 ]; then
    echo 5d
  elif [ $RUN -lt 8670 ]; then
    echo 5e
  elif [ $RUN -lt 8671 ]; then
    echo 5c
  elif [ $RUN -lt 8677 ]; then
    echo 5e
  elif [ $RUN -lt 8662 ]; then
    echo 5e
  elif [ $RUN -lt 8680 ]; then
    echo 5c
  elif [ $RUN -lt 8820 ]; then
    echo 5f
  elif [ $RUN -lt 8826 ]; then
    echo 5g
  elif [ $RUN -lt 8832 ]; then
    echo 5h
  elif [ $RUN -lt 8838 ]; then
    echo 5i
  elif [ $RUN -lt 8844 ]; then
    echo 5f
  elif [ $RUN -lt 8850 ]; then
    echo 5d
  elif [ $RUN -lt 8856 ]; then
    echo 5j
  elif [ $RUN -lt 8862 ]; then
    echo 5e
  elif [ $RUN -lt 8868 ]; then
    echo 5f
  elif [ $RUN -lt 8874 ]; then
    echo 5k
  elif [ $RUN -lt 8880 ]; then
    echo 5l
  elif [ $RUN -lt 8886 ]; then
    echo 5m
  elif [ $RUN -lt 8892 ]; then
    echo 5n
  elif [ $RUN -lt 8898 ]; then
    echo 5o
  elif [ $RUN -lt 8951 ]; then
    echo 5f
  elif [ $RUN -lt 9048 ]; then
    echo 5p
  elif [ $RUN -lt 9050 ]; then
    echo 5f
  elif [ $RUN -lt 9074 ]; then
    echo 5p
  elif [ $RUN -lt 9105 ]; then
    echo 5q
  else
    echo 5p
  fi
fi

