#!/bin/sh

# ibRunPeriod
#
# David Adams
# August 2020
#
# Return the run period for an Iceberg run numnber.

RUN=$1
SHORT=$2

if [ -z "$1" ]; then
  echo Usage: $0 RUN >&2
  echo "       $0 RUN short" >&2
  echo "Latter returns shortened period, e.g. 4 for 4b" >&2
  exit 1
fi

# If a range of runs is provided, use the first.
RUN=$(echo $RUN | sed 's/-.*//g')

if [ $RUN -lt 5360 ]; then
  echo 3
else
  if [ "$2" = short ]; then
    SPER=$($0 $RUN)
    echo ${SPER:0:1}
  elif [ $RUN -lt 6100 ]; then
    echo 4a
  elif [ $RUN -lt 6100 ]; then
    echo 4b
  elif [ $RUN -lt 8002 ]; then
    echo 4b
  elif [ $RUN -lt 8249 ]; then
    echo test
  elif [ $RUN -lt 8409 ]; then
    echo 5a
  elif [ $RUN -lt 8416 ]; then
    echo test
  elif [ $RUN -lt 8432 ]; then
    echo 5b
  elif [ $RUN -lt 8453 ]; then
    echo 5c
  elif [ $RUN -lt 8474 ]; then
    echo 5d
  elif [ $RUN -lt 8620 ]; then
    echo 5c
  elif [ $RUN -lt 8630 ]; then
    echo 5d
  elif [ $RUN -lt 8635 ]; then
    echo 5c
  elif [ $RUN -lt 8639 ]; then
    echo 5e
  elif [ $RUN -lt 8640 ]; then
    echo 5c
  elif [ $RUN -lt 8645 ]; then
    echo 5e
  elif [ $RUN -lt 8646 ]; then
    echo 5c
  elif [ $RUN -lt 8646 ]; then
    echo 5c
  elif [ $RUN -lt 8651 ]; then
    echo 5e
  elif [ $RUN -lt 8652 ]; then
    echo 5c
  elif [ $RUN -lt 8655 ]; then
    echo 5d
  elif [ $RUN -lt 8657 ]; then
    echo 5e
  elif [ $RUN -lt 8658 ]; then
    echo 5c
  elif [ $RUN -lt 8662 ]; then
    echo 5e
  elif [ $RUN -lt 8663 ]; then
    echo 5d
  elif [ $RUN -lt 8670 ]; then
    echo 5e
  elif [ $RUN -lt 8671 ]; then
    echo 5c
  elif [ $RUN -lt 8677 ]; then
    echo 5e
  elif [ $RUN -lt 8662 ]; then
    echo 5e
  elif [ $RUN -lt 8680 ]; then
    echo 5c
  elif [ $RUN -lt 8820 ]; then
    echo 5f
  elif [ $RUN -lt 8826 ]; then
    echo 5g
  elif [ $RUN -lt 8832 ]; then
    echo 5h
  elif [ $RUN -lt 8838 ]; then
    echo 5i
  elif [ $RUN -lt 8844 ]; then
    echo 5f
  elif [ $RUN -lt 8850 ]; then
    echo 5d
  elif [ $RUN -lt 8856 ]; then
    echo 5j
  elif [ $RUN -lt 8862 ]; then
    echo 5e
  elif [ $RUN -lt 8868 ]; then
    echo 5f
  elif [ $RUN -lt 8874 ]; then
    echo 5k
  elif [ $RUN -lt 8880 ]; then
    echo 5l
  elif [ $RUN -lt 8886 ]; then
    echo 5m
  elif [ $RUN -lt 8892 ]; then
    echo 5n
  elif [ $RUN -lt 8898 ]; then
    echo 5o
  elif [ $RUN -lt 8951 ]; then
    echo 5f
  elif [ $RUN -lt 9048 ]; then
    echo 5p
  elif [ $RUN -lt 9050 ]; then
    echo 5f
  elif [ $RUN -lt 9074 ]; then
    echo 5p
  elif [ $RUN -lt 9105 ]; then
    echo 5q
  elif [ $RUN -lt 9113 ]; then
    echo 5p
  elif [ $RUN -lt 9143 ]; then
    echo test
  elif [ $RUN -lt 9158 ]; then
    echo 5C22
  elif [ $RUN -lt 9168 ]; then
    echo 5C21
  elif [ $RUN -lt 9179 ]; then
    echo 5C22
  elif [ $RUN -lt 9190 ]; then
    echo 5C02
  elif [ $RUN -lt 9201 ]; then
    echo 5C12
  elif [ $RUN -lt 9212 ]; then
    echo 5C32
  elif [ $RUN -lt 9223 ]; then
    echo 5C22
  elif [ $RUN -lt 9234 ]; then
    echo 5C21
  elif [ $RUN -lt 9245 ]; then
    echo 5C20
  elif [ $RUN -lt 9256 ]; then
    echo 5C23
  elif [ $RUN -lt 9267 ]; then
    echo 5C22
  elif [ $RUN -lt 9278 ]; then
    echo 5C22l
  elif [ $RUN -lt 9289 ]; then
    echo 5C31
  elif [ $RUN -lt 9300 ]; then
    echo 5C33
  elif [ $RUN -lt 9311 ]; then
    echo 5C11
  elif [ $RUN -lt 9322 ]; then
    echo 5C13
  elif [ $RUN -lt 9338 ]; then
    echo 5C22
  elif [ $RUN -lt 9348 ]; then
    echo 5C21
  elif [ $RUN -lt 9431 ]; then
    echo 5C22
  elif [ $RUN -lt 9436 ]; then
    echo 5C01
  elif [ $RUN -lt 9441 ]; then
    echo 5C03
  elif [ $RUN -lt 9446 ]; then
    echo 5C02
  elif [ $RUN -lt 9451 ]; then
    echo 5C11
  elif [ $RUN -lt 9456 ]; then
    echo 5C13
  elif [ $RUN -lt 9461 ]; then
    echo 5C12
  elif [ $RUN -lt 9466 ]; then
    echo 5C21
  elif [ $RUN -lt 9471 ]; then
    echo 5C20
  elif [ $RUN -lt 9476 ]; then
    echo 5C23
  elif [ $RUN -lt 9488 ]; then
    echo 5C22
  elif [ $RUN -lt 9491 ]; then
    echo 5C33
  elif [ $RUN -lt 9518 ]; then
    echo 5C22
  elif [ $RUN -lt 9526 ]; then
    echo 5C21
  elif [ $RUN -lt 9537 ]; then
    echo 5C02
  elif [ $RUN -lt 9548 ]; then
    echo 5C01
  elif [ $RUN -lt 9559 ]; then
    echo 5C12
  elif [ $RUN -lt 9570 ]; then
    echo 5C11
  elif [ $RUN -lt 9580 ]; then
    echo 5C23
  elif [ $RUN -lt 9591 ]; then
    echo 5C20
  elif [ $RUN -lt 9602 ]; then
    echo 5C31
  elif [ $RUN -lt 9613 ]; then
    echo 5C32
  elif [ $RUN -lt 9714 ]; then
    echo 5C22
  elif [ $RUN -lt 9717 ]; then
    echo 5C01
  elif [ $RUN -lt 9719 ]; then
    echo 5C03
  elif [ $RUN -lt 9721 ]; then
    echo 5C02
  elif [ $RUN -lt 9723 ]; then
    echo 5C11
  elif [ $RUN -lt 9725 ]; then
    echo 5C13
  elif [ $RUN -lt 9727 ]; then
    echo 5C12
  elif [ $RUN -lt 9729 ]; then
    echo 5C21
  elif [ $RUN -lt 9731 ]; then
    echo 5C20
  elif [ $RUN -lt 9733 ]; then
    echo 5C23
  elif [ $RUN -lt 9744 ]; then
    echo 5C22
  else
    echo 6
  fi
fi

