#!/bin/sh

RUN=$1
EVT=$2
if [ -z "$2" -o "$1" = "-h" ]; then
  echo Usage: $0 RUN EVENT
  exit 0
fi
SRUN=$RUN
SEVT=$EVT
while [ ${#SRUN} -lt 6 ]; do SRUN="0"$SRUN; done
while [ ${#SEVT} -lt 6 ]; do SEVT="0"$SEVT; done
SPER=$(ibRunPeriod $RUN)
RUNDIR=$(ls -d run_iceberg${SPER}_dqm1/iceberg${SRUN}/event${SEVT})
if [ ! -n "$RUNDIR" ]; then
  echo Run directory not found for run $RUN event $EVT
  exit 1
fi
echo Taking plots from $RUNDIR

OUTBASEDIR=$HOME/wwwdune/protodune/iceberg/data/dqm1
OUTRUNDIR=$OUTBASEDIR/run$SRUN
if [ ! -r $OUTRUNDIR ]; then
  echo Creating $OUTRUNDIR
  mkdir $OUTRUNDIR
fi
OUTDIR=$OUTRUNDIR/event$SEVT
if [ ! -r $OUTDIR ]; then
  echo Creating $OUTDIR
  mkdir $OUTDIR
fi
echo Copying from $RUNDIR to $OUTDIR
cp $RUNDIR/* $OUTDIR
makeIndex $OUTDIR k
makeIndex $OUTRUNDIR k
makeIndex $OUTBASEDIR k

exit 0

