#!/bin/sh

# Stage a duneproc dataset in FNAM dcache.

tail_log() {
  LOG=$1
  echo
  echo Displaying log at $LOG.
  echo Interrupt at any time with ^C.
  tail -f $LOG
}

# Parse arguments.
FORCE=false
while true; do
  if [ $1 = '-f' ]; then
    FORCE=true
  elif [ ${1:0:1} = '-' ]; then
    echo Invalid option: $1
    exit 1
  else
    break
  fi
  shift
done
DSTNAM=$1

COM=$(basename $0)
if [ -z "$DSTNAM" -o "$DSTNAM" = "-h" -o -n "$2" ]; then
  echo "Usage: $COM [-f] PAT"
  echo "  where PAT is one of the following:"DSTNAME
  echo "        DSTNAM - stage the list of files in DUNE dataset DSTNAME, i.e."
  echo "                 from DSTNAME.txt in the tree $HOME/data/dune/datasets."
  echo "      NAME.SUF -  stage the file NAME.SUF"
  echo "  RTYP-RUN-EVT - Stage the single file holding the raw data for the"
  echo "                 given run and event in run type or alias RTYP e.g."
  echo "                 pdsp, iceberg, hdcb, vdbcb, vdtcb."
  echo "File are staged at FNAL."
  echo "Options:"
  echo "  -f - Stage even if an old staging log is found"
  exit 0
fi

# Find the dataset definition file of single file name.
DSTDIR=$HOME/data/dune/datasets
DSTFIL=$(find $DSTDIR -name $DSTNAM.txt)
FNAM=
if [ -z "$DSTFIL" ]; then
  ARGS=($(echo $DSTNAM | sed s'/-/ /g'))
  if [ ${#ARGS[*]} = 3 ]; then
    FNAM=$(findRunFiles ${ARGS[*]} | sed 's/ .*//g')
  else
    SUF=$(echo $DSTNAM | grep '\.')
    FNAM=$DSTNAM
  fi
  if [ -z "$FNAM" ]; then
    echo Dataset not found: $DSTNAM
    exit 1
  fi
fi

# Define log for the staging job.
if [ ! -d $DSTDIR/logs ]; then mkdir $DSTDIR/logs; fi
LOG=$DSTDIR/logs/stage_$DSTNAM.log
if [ -r $LOG ]; then
  if [ $FORCE = true ]; then
    echo Removing Old staging log:
    ls -ls $LOG
    tail $LOG
    rm $LOG
  else
    echo It appears dataset is being or has been staged:
    echo '-----------------------------'
    echo '.'
    echo '.'
    echo '.'
    tail $LOG
    echo '-----------------------------'
    echo Remove $LOG or rerun with -f to stage again.
  fi
  exit 0
fi

# Make sure we have a proxy.
dunerun-check-proxy
echo

# Create the sam query.
if [ -n "$FNAM" ]; then
  QUERY="file_name = $FNAM"
else
  FIRST=true
  QUERY="file_name in ("
  SEP=
  for FNAM in $(cat $DSTFIL); do
    echo $FNAM
    QUERY=${QUERY}${SEP}${FNAM}
    SEP=", "
  done
  QUERY="${QUERY})"
fi
echo QUERY: $QUERY
#samweb list-files $QUERY

# Create sam dataset
SDSNAM=${USER}_$DSTNAM
samweb create-definition $SDSNAM "$QUERY"

# Make sure node name ends in .fnal.gov.
NODE=$(hostname)
if [ -z "$NODE" ]; then
  NODE=unknown
fi
if [ ${NODE: -9} != .fnal.gov ]; then
  NODE=$NODE.fnal.gov
fi

# Stage dataset
echo "Staging dataset $SDSNAM" >>$LOG
COM="samweb prestage-dataset --node=$NODE --defname=$SDSNAM"
echo Staging command: $COM
date >>$LOG
echo >>$LOG
nohup sh -c "$COM; echo; date; echo Done">>$LOG 2>&1 &
sleep 2
echo
echo Log is $LOG
tail_log $LOG
